# Generated by Django 4.1.7 on 2023-03-25 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='avatar',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='avatar_pics'),
        ),
    ]
