# Generated by Django 4.1.7 on 2023-03-27 19:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csrf', models.CharField(max_length=32)),
                ('agent', models.CharField(max_length=255)),
                ('visited', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('device', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-visited'],
            },
            managers=[
                ('visit', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='visitor',
            index=models.Index(fields=['visited'], name='blog_visito_visited_4a34c4_idx'),
        ),
    ]
