# Generated by Django 4.1.7 on 2023-03-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_visitor_visitor_blog_visito_visited_4a34c4_idx'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='visitor',
            managers=[
            ],
        ),
    ]
