# Generated by Django 4.1.7 on 2023-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_visitor_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='active',
        ),
        migrations.AddField(
            model_name='visitor',
            name='requests',
            field=models.BigIntegerField(default=0),
        ),
    ]
