# Generated by Django 4.1.7 on 2023-03-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_visitor_active_visitor_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visits',
            field=models.BigIntegerField(default=0),
        ),
    ]
