# Generated by Django 4.1.7 on 2023-03-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_visitor_visits'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='ip',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='visitor',
            name='os',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='visitor',
            name='processor',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
