# Generated by Django 4.1.7 on 2023-03-27 21:29

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_managers_visitor_ip_visitor_os_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('commented', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='visitor',
            old_name='processor',
            new_name='host',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='ip',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
